### ISSUE TITLE
source doc not available in Read The Docs

### ISSUE THREAD

**Issue by loicpw** [loicpw/clichain#1]
The source documentation is currently not available in Read The Docs because Read The Docs uses a python3.5 environment, which causes the build to crash since this version is not supported (due to use of 'f' strings) then 'autodoc' statements fail in the doc.

A Read the Docs YAML Config file in the root directory of the project should fix the problem, such as:

```
# .readthedocs.yml

build:
  image: latest

python:
  version: 3.7
  setup_py_install: true
```
